name: Run Snap Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Pega o código do repositório
      - name: Checkout
        uses: actions/checkout@v3

      # Configura Node.js (escolha a versão do seu projeto)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instala dependências
      - name: Install dependencies
        run: npm install

      # Roda os testes
      - name: Run tests
        run: npm test
